import e2edutch.coref_model
from collections import OrderedDict

test_config = {'max_top_antecedents': 30,
 'max_training_sentences': 30,
 'top_span_ratio': 0.4,
 'filter_widths': [3, 4, 5],
 'filter_size': 50,
 'char_embedding_size': 8,
 'char_vocab_path': 'data/char_vocab.dutch.txt',
 'context_embeddings': OrderedDict([('path', 'data/fasttext.300.vec'),
              ('size', 300),
              ('cased', True)]),
 'head_embeddings': OrderedDict([('path', 'data/fasttext.300.vec'),
              ('size', 300),
              ('cased', True)]),
 'contextualization_size': 200,
 'contextualization_layers': 3,
 'ffnn_size': 150,
 'ffnn_depth': 2,
 'feature_size': 20,
 'max_span_width': 30,
 'use_metadata': True,
 'use_features': True,
 'model_heads': True,
 'coref_depth': 2,
 'lm_layers': 1,
 'lm_size': 768,
 'coarse_to_fine': True,
 'max_gradient_norm': 5.0,
 'lstm_dropout_rate': 0.4,
 'lexical_dropout_rate': 0.5,
 'dropout_rate': 0.2,
 'optimizer': 'adam',
 'learning_rate': 0.001,
 'decay_rate': 0.999,
 'decay_frequency': 100,
 'train_path': 'data/train.dutch.jsonlines',
 'eval_path': 'data/dev.dutch.jsonlines',
 'conll_eval_path': 'data/dev.dutch.conll',
 'lm_model_name': 'bertje',
 'lm_path': 'data/bertje_cache.hdf5',
 'genres': ['all'],
 'eval_frequency': 5000,
 'report_frequency': 100,
 'use_gold': False,
 'log_root': 'logs',
 'cluster': OrderedDict([('addresses',
               OrderedDict([('ps', ['localhost:2222']),
                            ('worker',
                             ['localhost:2223', 'localhost:2224'])])),
              ('gpus', [0, 1])]),
 'log_dir': 'logs/best'
 }


def test_coref_model():
    model = e2edutch.coref_model.CorefModel(test_config)
    assert model.predictions is not None
