# Config file for automatic testing at travis-ci.org
dist: xenial   # required for Python >= 3.7
language: python
jobs:
  include:
    - name: "Python 3.6 on Xenial Linux"
      python: 3.6
      dist: xenial
    - name: "Python 3.7 on Xenial Linux"
      python: 3.7
      dist: xenial
    - name: "Python 3.7 on macOS"
      os: osx
      osx_image: xcode11.2
      language: generic

# command to install dependencies
install:
  - pip install --upgrade setuptools
  - pip install -r requirements.txt
  - ./scripts/setup_all.sh
  - python setup.py install

# command to run tests
script: pytest test
